{
  "headers": {
    "client_id": "a",
    "client_secret": "b",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "b2c6e541-eda6-470b-ad7c-b73e0b7952c4",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "192"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/bookings",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/bookings",
  "listenerPath": "/api/*",
  "relativePath": "/api/bookings",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/bookings",
  "rawRequestPath": "/api/bookings",
  "remoteAddress": "/127.0.0.1:62982",
  "requestPath": "/api/bookings"
}