http:
  host: "0.0.0.0"
  port: "8081"

autoDiscovery:
  Id: "17509245"
  flowName: "bookmyshow-prc-api-main"
  
httpRequest:
  host: "bms-tickets-sys-api.us-e2.cloudhub.io"
  basePath: "/api"
  getOffersPath: "/offers"
  createOrdersPath: "/tickets"